" 模块化管理 vim 的配置文件

" 插件加载
source $HOME/.vim/vim-plug/plugins.vim

" 基本配置
source $HOME/.vim/general/settings.vim

" 按键映射
source $HOME/.vim/keys/mappings.vim
source $HOME/.vim/keys/which-key.vim

" 插件配置
" source $HOME/.vim/plug-config/ycm.vim
source $HOME/.vim/plug-config/vim-gutentags.vim
if has_key(plugs, 'vim-commentary')
 source $HOME/.vim/plug-config/vim-commentary.vim
endif
source $HOME/.vim/plug-config/taglist.vim
" vimwiki
" if has_key(plugs, 'vimwiki')
 " source $HOME/.vim/plug-config/vimwiki.vim
" endif
" LeaderF
if has_key(plugs, 'LeaderF')
 source $HOME/.vim/plug-config/LeaderF.vim
endif
" sneak
if has_key(plugs, 'vim-sneak')
 source $HOME/.vim/plug-config/sneak.vim
endif

